server:
  port: ${PORT:8080}

spring:
  # CRÍTICO: Deshabilitar CORS automático de Spring Boot
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration
  web:
    cors:
      enabled: false

  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  jackson:
    time-zone: Europe/Madrid

  # AÑADIR - Configuración JWT
  security:
    jwt:
      secret: ${JWT_SECRET:tu-clave-secreta-super-segura-256-bits}
      expiration: 86400000  # 24 horas

# OpenAI - MANTENER
openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions

# Twilio - MANTENER
twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

# Multi-tenant - MANTENER
default:
  tenant:
    id: ${DEFAULT_TENANT_ID:tenant_demo_001}

# Logging mejorado para debug
logging:
  level:
    root: INFO
    com.peluqueria: DEBUG
    com.peluqueria.recepcionista_virtual.security: DEBUG
    com.peluqueria.recepcionista_virtual.controller: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.cors: DEBUG