server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      connection-timeout: 60000  # 60 segundos
      idle-timeout: 300000
      max-lifetime: 600000  # 10 minutos
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update  # Mantenemos UPDATE
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          provider_disables_autocommit: true
        # CRÍTICO: Evita que Hibernate mantenga conexiones abiertas mucho tiempo
        c3p0:
          idle_test_period: 30
        # Reduce el trabajo de metadata
        temp:
          use_jdbc_metadata_defaults: false
        # Importante para AWS RDS
        schema_update:
          unique_constraint_strategy: RECREATE_QUIETLY
    show-sql: false
    open-in-view: false  # Importante para no mantener conexiones abiertas

    features:
      compliance:
        enabled: ${COMPLIANCE_ENABLED:false}  # Activar/desactivar RGPD
        rgpd:
          aviso-obligatorio: ${RGPD_AVISO:true}
          retencion-dias: ${RGPD_RETENTION:30}
          requiere-consentimiento: ${RGPD_CONSENT:true}

      call-forwarding:
        enabled: ${FORWARDING_ENABLED:false}  # Activar/desactivar desvíos
        identify-by-forwarded: ${IDENTIFY_FORWARDED:true}
        fallback-tenant: ${DEFAULT_TENANT:tenant_demo_001}

      multi-number:
        enabled: ${MULTI_NUMBER_ENABLED:false}  # Múltiples números por tenant
        spanish-numbers: ${SPANISH_NUMBERS:true}

      ai-enhanced:
        compliance-prompts: ${AI_COMPLIANCE:true}  # GPT-4 genera avisos legales
        personalized-greetings: ${AI_GREETINGS:true}

    # Configuración Twilio España
    twilio:
      region: spain
      voice:
        language: es-ES
        voice-type: Polly.Lucia  # Voz española femenina
        backup-voice: Polly.Conchita
      numbers:
        country-code: "+34"

    # Textos legales (personalizables por tenant)
    legal:
      default-rgpd-notice: |
        Gracias por llamar. Le informamos que esta llamada puede ser grabada 
        con fines de calidad del servicio. Si continúa, acepta estas condiciones.
      short-notice: "Esta llamada puede ser grabada. ¿En qué puedo ayudarle?"

    # Logging mejorado
    logging:
      level:
        com.peluqueria.recepcionista_virtual.compliance: ${LOG_LEVEL_COMPLIANCE:INFO}
        com.peluqueria.recepcionista_virtual.twilio: ${LOG_LEVEL_TWILIO:DEBUG}